name: Build and Create Releases

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  create_release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-android:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          filename: "keystore"
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Set Gradle Properties for Android
        run: echo "android.useAndroidX=true" >> gradle.properties

      - name: Build Android AAB
        run: ./gradlew composeApp:buRelease -Pandroid.injected.signin.store.file=${{ steps.decode_keystore.outputs.filePath }} -Pandroid.injected.signin.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -Pandroid.injected.signin.store.alias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} -Pandroid.injected.signin.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Build Android APK
        run: ./gradlew composeApp:assembleRelease -Pandroid.injected.signin.store.file=${{ steps.decode_keystore.outputs.filePath }} -Pandroid.injected.signin.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -Pandroid.injected.signin.store.alias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} -Pandroid.injected.signin.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Upload Release AAB Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.output1 }}
          asset_path: composeApp/build/outputs/bundle/release/composeApp-release.aab
          asset_name: buscaminas-${{ github.ref_name }}.aab
          asset_content_type: application/x-authorware-bin

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore ${{ secrets.ANDROID_KEYSTORE_FILE }} \
            -storepass ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }} \
            -keypass ${{ ANDROID_KEYSTORE_PASSWORD }} \
            composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk \
            "$ANDROID_KEYSTORE_ALIAS"
        env:
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}

      - name: Verify APK Signature
        run: jarsigner -verify -verbose -certs composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk

      - name: Rename APK to Match Expected Name
        run: mv composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk composeApp/build/outputs/apk/release/composeApp-release.apk

      - name: Upload Release APK Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.output1 }}
          asset_path: composeApp/build/outputs/apk/release/composeApp-release.apk
          asset_name: buscaminas-${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive

  build-windows:
    permissions: write-all
    runs-on: windows-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build .msi
        run: .\gradlew.bat composeApp:packageReleaseMsi
        shell: cmd

      - name: Get Version Name
        id: get_version_name
        shell: bash
        run: echo "version_name=$(./.github/scripts/get_version_name.sh versions.properties)" >> $GITHUB_OUTPUT

      - name: Upload Release MSI Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/msi/Buscaminas-${{ steps.get_version_name.outputs.version_name }}.msi
          asset_name: buscaminas-${{ github.ref_name }}.msi
          asset_content_type: application/octet-stream

  build-macos:
    permissions: write-all
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Set Gradle Properties for Android
        run: echo "android.useAndroidX=true" >> gradle.properties

      - name: Build .dmg
        run: ./gradlew composeApp:packageReleaseDmg -Xbinary=bundleId=com.charr0max.buscaminas.Buscaminas

      - name: Get Version Name
        id: get_version_name
        shell: bash
        run: echo "version_name=$(./.github/scripts/get_version_name.sh versions.properties)" >> $GITHUB_OUTPUT

      - name: Upload Release DMG Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/dmg/Buscaminas-${{ steps.get_version_name.outputs.version_name }}.dmg
          asset_name: buscaminas-${{ github.ref_name }}.dmg
          asset_content_type: application/octet-stream