name: Version and Release

on:
  pull_request:
    types:
      - closed

jobs:
  versioning:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read Current Version
        id: get_version
        run: |
          MAJOR=$(grep 'versionMajor' versions.properties | cut -d'=' -f2)
          MINOR=$(grep 'versionMinor' versions.properties | cut -d'=' -f2)
          PATCH=$(grep 'versionPatch' versions.properties | cut -d'=' -f2)
          CODE=$(grep 'versionCode' versions.properties | cut -d'=' -f2)
          
          PATCH=$((PATCH + 1)) # Increment Patch version
          CODE=$((CODE + 1))   # Increment Version Code

          echo "NEW_VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
          echo "NEW_CODE=$CODE" >> $GITHUB_ENV

          echo "versionMajor=$MAJOR" > versions.properties
          echo "versionMinor=$MINOR" >> versions.properties
          echo "versionPatch=$PATCH" >> versions.properties
          echo "versionCode=$CODE" >> versions.properties
          
      - name: Debug Git Remote URL
        run: git remote -v

      - name: Debug GH_PAT
        run:
          echo "GH_PAT length: ${#GH_PAT}"

      - name: Commit and Push New Version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add versions.properties
          git commit -m "🚀 Bump version to $NEW_VERSION (Code: $NEW_CODE)"

      - name: Push Version Update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

          git push origin master

      - name: Create Git Tag
        run: |
          git tag v$NEW_VERSION
          git push origin v$NEW_VERSION

      - name: Trigger Build & Release Pipeline
        run: |
          curl -X POST -u "x-access-token:${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches" \
          -d '{"ref": "master"}'